<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8cfhg4q\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8cfhg4q/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container8cfhg4q.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container8cfhg4q\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container8cfhg4q\appDevDebugProjectContainer(array(
    'container.build_hash' => '8cfhg4q',
    'container.build_id' => '84f25d6f',
    'container.build_time' => 1529850115,
), __DIR__.\DIRECTORY_SEPARATOR.'Container8cfhg4q');
